### ISSUE TITLE
Private

### ISSUE THREAD

**Issue by woutervanwijk** [fryette/webview_cookie_manager#18]
Just an idea: Private mode is not possible with webview now. Make it possible to do a private mode: store all cookies on start, clean them and (optionally) restore the cookies after the webview closes

**Comment by yankai3306** [comment]
if cookie.value =  "{\"123.123.123.123\": 1234}:5678:9999"
webviewCookieManager.getCookies(url) is error.
FormatException: Invalid character in cookie value, code unit: '92' (at character 2)

**Comment by fryette** [comment]
@yankai3306 created a separate issue for that

**Comment by yankai3306** [comment]
If the value in cookies contains \", this method will fail to parse in Dart.

**Comment by yankai3306** [comment]
'\"'

**Comment by Vovanella95** [comment]
This issue is raised because " and spaces are not allowed in Cookie value. This exception raises in http_headers.dart file from dart:http lib. You just need to use valid cookie or add validation before assign it to Cookie(name, value).

@fryette @yankai3306

**Comment by fryette** [comment]
@yankai3306  let's move to here
https://github.com/amag2511/webview_cookie_manager/issues/19

**Comment by fryette** [comment]
It's not the aim of the current plugin to provide anonymous mode.
Close for now.
