### ISSUE TITLE
deprecated use

### ISSUE THREAD

**Issue by StillerJim** [fryette/webview_cookie_manager#22]
I noticed this warning while compiling in android studio for android release build. 
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\webview_cookie_manager-1.0.4\android\src\main\java\io\flutter\plugins\webview_cookie_manager\WebviewCookieManagerPlugin.java uses or overrides a deprecated API.

is it ok?

**Comment by fryette** [comment]
@StillerJim thx for the issue!
I will take a look at it this week.
Everything should be fine and this warning should not affect your app or publish process.
Anyway this of course should be fixed and will be fixed.

Have a nice day!

**Comment by swarajhoster** [comment]
Basically, the error will not cause, anything wrong in production, but to fix it, follow the steps below:- 

This answer is given on the basis of the web-view version  -->

> webview_cookie_manager: ^2.0.6

In your app-level build.gradle file 
**Change your minSdkVersion to 23** -->

> minSdkVersion 23

**Also, enable multiDex = true -->**

> multiDexEnabled true

>     defaultConfig {
>         applicationId "dev.appName.club"
>         minSdkVersion 23
>         targetSdkVersion flutter.targetSdkVersion
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>         multiDexEnabled true
>     }

This should solve the error.
Happy Coding ...
