### ISSUE TITLE
Remove Cookie 

### ISSUE THREAD

**Issue by ronolivarph** [fryette/webview_cookie_manager#23]
Calling removeCookie removes all cookies 
![image](https://user-images.githubusercontent.com/20569099/99608758-7e026f00-2a49-11eb-881d-59f99e4c2df1.png)

**Comment by fryette** [comment]
@ronolivarph Sorry for the late response.

You can clear cookies by hand by setting the expiration date for needed cookies and then save it.

But I agree, that is a great drawback.

I will fix it and provide a new version.
