### ISSUE TITLE
Cannot convert value of type 'Bool' to expected argument type '[Bool]'

### ISSUE THREAD

**Issue by bert1100** [fryette/webview_cookie_manager#30]
<img width="1386" alt="9374D563-C76B-434B-A494-E7589D81FAA7" src="https://user-images.githubusercontent.com/189849/105680638-f9d9d580-5f2a-11eb-9236-a23781b1269b.png">

i  use webview_cookie_manager 1.0.6

**Comment by michaelgobbers** [comment]
Same issue here. Started popping up today.

**Comment by jordanliu** [comment]
@michaelgobbers @bert1100 Set webview_cookie_manager version fixed to 1.0.5 and give it a try

**Comment by bru95** [comment]
Same issue here ...

**Comment by fryette** [comment]
will push package soon 1.0.7

**Comment by bru95** [comment]
@fryette in 1.0.5 everything is ok

**Comment by fryette** [comment]
@bru95 please confirm that in 1.0.7 everything is fine

**Comment by bru95** [comment]
Yes, 1.0.7 is ok.

Thanks!
