### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by henrikvedal** [fryette/webview_cookie_manager#32]
Is there any plan on migrating to null safety?

**Comment by fryette** [comment]
After release will try to find a time and move it to null safety

**Comment by mzdm** [comment]
I can raise a PR today if you didn't already start yet @fryette

**Comment by fryette** [comment]
@mzdm Would be great!

**Comment by fryette** [comment]
@mzdm just published a null safety version together with a fix from @Mol0ko 
Would be great if you can take a look on it.
Thanks!

**Comment by fryette** [comment]
@mzdm published 2.0 version

Thanks for your contribution.

Will close issue. Feel free to open if something went wrong
