### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'bool'

### ISSUE THREAD

**Issue by stjfk** [fryette/webview_cookie_manager#37]
Hi, 
First of all, thank you for your work.

After upgrading to the new version (if the site has been visited before) I started getting this error

flutter: 2.0.1
webview_cookie_manager: 2.0.0-nullsafety.0

![image](https://user-images.githubusercontent.com/70009860/110239777-c3e03600-7f59-11eb-8f2e-3b60d26a0cd5.png)

**Comment by mzdm** [comment]
Try to switch to `beta` Flutter channel. Looking at `Cookie` seems like arguments must be non-nullable on `stable` but on `beta/master` they can be nullable. 

This case should be handled through with `??` check in the map line 38.
