### ISSUE TITLE
Unable to pass json as a cookie

### ISSUE THREAD

**Issue by hussainhyder23** [fryette/webview_cookie_manager#41]
I am trying to pass the JSON response as my cookie and it fails showing the following error 

<img width="928" alt="Screenshot 2021-04-21 at 3 31 26 PM" src="https://user-images.githubusercontent.com/43246921/115535711-a4595e80-a2b6-11eb-8f6b-05539aa0d671.png">

**Comment by fryette** [comment]
Probably it related to #44 
Could you please recheck with new version?

**Comment by fryette** [comment]
close because of inactivity.
Feel free to reopen
